# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        require_serial: true
        language: system
        types: [ python ]
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        require_serial: true
        language: system
        types: [ python ]
  - repo: https://github.com/iterative/dvc
    # rev should be set to a specific revision (e.g. 2.9.5) since pre-commit
    # does not allow using mutable references.
    rev: 3.27.0
    hooks:
      - id: dvc-pre-commit
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - push
      - id: dvc-post-checkout
        additional_dependencies:
          - .[all]
        language_version: python3
        stages:
          - post-checkout
        always_run: true
