stages:
  install:
    cmd: poetry install

  load_env:
    cmd: python src/utils/load_env.py
    deps:
    - .env

  data_download:
    cmd: python src/modules/data_download/data_download.py
    deps:
    - src/modules/data_download/data_download.py
    - data/surveys/gcro-2021.dta
    - data/surveys/gcro-2018.dta
    - data/surveys/gcro-2016.dta
    - data/shapefiles/2011
    - data/shapefiles/2016
    - data/shapefiles/2020
#    outs:
#    - data/input

  preprocess:
    cmd: python src/modules/preprocessing/preprocess.py
    deps:
    - src/modules/preprocessing/preprocess.py
#    - data/input
#    outs:
#    - data/intermediate

  train:
    cmd: python src/modules/training/train.py
    deps:
    - src/modules/training/train.py
#    - data/intermediate
#    outs:
#    - outputs/model.pkl

  evaluate:
    cmd: python src/modules/evaluation/evaluate.py outputs/model.pkl data/intermediate
    deps:
    - src/modules/evaluation/evaluate.py
#    - data/intermediate
#    - outputs/model.pkl
#    outs:
#    - eval
