# NB: Script must be included in deps in order to trigger changed stage
stages:
  install:
    cmd: poetry install

  load_env:
    cmd: python src/utils/load_env.py
    deps:
    - src/utils/load_env.py
    - .env

  shapefile_processing:
    cmd: python src/modules/1_shapefile_processing/shapefile_process.py
    deps:
    - src/modules/1_shapefile_processing/shapefile_process.py
    - data/shapefiles/2011
    - data/shapefiles/2016
    - data/shapefiles/2020
    outs:
    - outputs/processed-shapefile/2011/gauteng-boundary.geojson
    - outputs/processed-shapefile/2011/gauteng-boundary-unprocessed.geojson
    - outputs/processed-shapefile/2011/gauteng-wards.geojson
    - outputs/processed-shapefile/2011/gauteng-boundary.png
    - outputs/processed-shapefile/2011/gauteng-boundary-unprocessed.png
    - outputs/processed-shapefile/2011/gauteng-wards.png
    - outputs/processed-shapefile/2011/za-wards.png
    - outputs/processed-shapefile/2016/gauteng-boundary.geojson
    - outputs/processed-shapefile/2016/gauteng-boundary-unprocessed.geojson
    - outputs/processed-shapefile/2016/gauteng-wards.geojson
    - outputs/processed-shapefile/2016/gauteng-boundary.png
    - outputs/processed-shapefile/2016/gauteng-boundary-unprocessed.png
    - outputs/processed-shapefile/2016/gauteng-wards.png
    - outputs/processed-shapefile/2016/za-wards.png
    - outputs/processed-shapefile/2020/gauteng-boundary.geojson
    - outputs/processed-shapefile/2020/gauteng-boundary-unprocessed.geojson
    - outputs/processed-shapefile/2020/gauteng-wards.geojson
    - outputs/processed-shapefile/2020/gauteng-boundary.png
    - outputs/processed-shapefile/2020/gauteng-boundary-unprocessed.png
    - outputs/processed-shapefile/2020/gauteng-wards.png
    - outputs/processed-shapefile/2020/za-wards.png

  gcro_processing:
    cmd: python src/modules/2_gcro_processing/gcro_process.py
    deps:
    - src/modules/2_gcro_processing/gcro_process.py
    - data/surveys/gcro-2021.dta
    - data/surveys/gcro-2018.dta
    - data/surveys/gcro-2016.dta
    outs:
    - outputs/processed-gcro/2021/gcro-column-datatypes.json
    - outputs/processed-gcro/2021/gcro-date-info.json
    - outputs/processed-gcro/2021/gcro-clustered-data.csv
    - outputs/processed-gcro/2018/gcro-column-datatypes.json
    - outputs/processed-gcro/2018/gcro-date-info.json
    - outputs/processed-gcro/2018/gcro-clustered-data.csv
    - outputs/processed-gcro/2016/gcro-column-datatypes.json
    - outputs/processed-gcro/2016/gcro-date-info.json
    - outputs/processed-gcro/2016/gcro-clustered-data.csv

  data_download:
    cmd: python src/modules/3_data_download/data_download.py
    deps:
    - src/modules/3_data_download/data_download.py
    - data/surveys/gcro-2021.dta
    - data/surveys/gcro-2018.dta
    - data/surveys/gcro-2016.dta
    - data/basemap-metadata/basemap-metadata.json

  gcro_shapefile_merge:
    cmd: python src/modules/4_gcro_shapefile_merge/gcro_shapefile_merge.py
    deps:
    - src/modules/4_gcro_shapefile_merge/gcro_shapefile_merge.py
    - outputs/processed-shapefile/2020/gauteng-wards.geojson
    - outputs/processed-shapefile/2016/gauteng-wards.geojson
    - outputs/processed-shapefile/2011/gauteng-wards.geojson
    - outputs/processed-gcro/2021/gcro-clustered-data.csv
    - outputs/processed-gcro/2018/gcro-clustered-data.csv
    - outputs/processed-gcro/2016/gcro-clustered-data.csv
    outs:
    - outputs/merged/gauteng-qol.geojson
    - outputs/merged/2021/gauteng-qol.geojson
    - outputs/merged/2021/gauteng-qol.png
    - outputs/merged/2018/gauteng-qol.geojson
    - outputs/merged/2018/gauteng-qol.png
    - outputs/merged/2016/gauteng-qol.geojson
    - outputs/merged/2016/gauteng-qol.png

  tiling:
    cmd: python src/modules/5_tiling/tile_images.py
    deps:
    - src/modules/5_tiling/tile_images.py
    - src/modules/5_tiling/tile_image.py
    - src/modules/5_tiling/tile.sbatch
    - src/modules/5_tiling/tile_slurm.py
    params:
    - preprocessing.crop_size
    outs:
    - outputs/tiles/tile-transforms.geojson

  tile_cluster_matching:
    cmd: python src/modules/6_tile_cluster_matching/match_tiles.py
    deps:
    - src/modules/6_tile_cluster_matching/match_tiles.py
    - outputs/merged/gauteng-qol.geojson
    - outputs/tiles/tile-transforms.geojson
    params:
    - preprocessing.drop_overlap
    outs:
    - outputs/matched/gauteng-qol-cluster-tiles.geojson
    - outputs/matched/2018-gauteng-qol-cluster-tiles.png
    - outputs/matched/2021-gauteng-qol-cluster-tiles.png

  train_test_split:
    cmd: python src/modules/7_data_splitting/split_data.py
    deps:
    - src/modules/7_data_splitting/split_data.py
    - outputs/matched/gauteng-qol-cluster-tiles.geojson
    params:
    - split
    - constants.random_seed
    outs:
    - outputs/model/train-test-split.geojson
    - outputs/model/train-stats.csv
    - outputs/model/test-stats.csv

  train:
    cmd: python src/modules/8_training/train.py
    deps:
    - src/modules/8_training/train.py
    - src/models
    - outputs/model/train-test-split.geojson
    params:
    - split
    - train
    - constants.random_seed
    outs:
    #      - outputs/model/folds
    - outputs/model/final.keras
    - outputs/model/model_summary.txt
    - outputs/model/train-validation-test-split.geojson

  evaluate:
    cmd: python src/modules/9_evaluation/evaluate.py
    deps:
    - src/modules/9_evaluation/evaluate.py
    - outputs/model/train-test-split.geojson
    - outputs/model/final.keras
    outs:
    - outputs/eval/train_scores.pkl
    - outputs/eval/validation_scores.pkl
    - outputs/eval/test_scores.pkl

  results:
    cmd: python src/modules/10_predictions_and_plots/main.py
    deps:
    - src/modules/10_predictions_and_plots/main.py
    - src/modules/10_predictions_and_plots/predict.py
    - src/modules/10_predictions_and_plots/plot.py
    - outputs/model/train-test-split.geojson
    - outputs/model/final.keras
    outs:
    - outputs/results

  #  generate_grid:
  #    cmd: python src/modules/grid_generation/generate_grid.py
  #    deps:
  #      - src/modules/grid_generation/generate_grid.py
  #      - outputs/merged/gauteng-qol.geojson
  #    outs:
  #      - outputs/grid/grid-overlay.png
  #      - outputs/grid/grid-gauteng-qol.png
  #      - outputs/grid/qol-labelled-grid.csv
  #
  #  mosaiks_prediction:
  #    cmd: python src/modules/mosaiks_prediction/predict.py
  #    deps:
  #      - src/modules/mosaiks_prediction/predict.py
  #      - data/mosaiks-features/mosaiks_features.csv
  #      - outputs/grid/qol-labelled-grid.csv
  #    outs:
  #      - outputs/mosaiks-prediction/ols-observed-vs-predicted.png
  #      - outputs/mosaiks-prediction/ols-observed.png
  #      - outputs/mosaiks-prediction/ols-predicted.png
  #      - outputs/mosaiks-prediction/ridge-observed-vs-predicted.png
  #      - outputs/mosaiks-prediction/ridge-observed.png
  #      - outputs/mosaiks-prediction/ridge-predicted.png
artifacts:
  resnet:
    path: resnet
    type: model
  fold_0:
    path: outputs/model/folds/fold_0.keras
    type: model
  fold_1:
    path: outputs/model/folds/fold_1.keras
    type: model
  fold_2:
    path: outputs/model/folds/fold_2.keras
    type: model
  fold_3:
    path: outputs/model/folds/fold_3.keras
    type: model
  fold_4:
    path: outputs/model/folds/fold_4.keras
    type: model
  final:
    path: outputs/model/final.keras
    type: model
metrics:
- outputs/eval/metrics.json
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
