constants:
  random_seed: 42

preprocessing:
  drop_overlap: true
  crop_size: 128

split:
  test_size: 0.2
  val_size: 0.2
  folds: 5
  group_by_ward: true

train:
  # One of services, socioeconomic_status, government_satisfaction,
  # life_satisfaction, health, safety, participation, qol_index
  label: qol_index
  # Loss to use for training
  loss: mean_squared_error
  # Learning rate to use for training
  learning_rate: 0.0001
  # Group training data by ward
  group_by_ward: true
  # Up number epochs
  epochs: 150
  # Model name. One of: resnet50v2
  model_name: resnet50v2

model:
  resnet50v2:
    fc_units: 1024
    dropout_rate: 0.2
