constants:
  random_seed: 42

preprocessing:
  # Whether to drop tiles that overlap across wards
  drop_overlap: true
  # Crop size of tile
  crop_size: 256
  # Number of channels expected in image (RGB => 3)
  channels: 3
  # Select year during data split
  # One of all, 2018, 2021
  year: 'all'
  # Select specific wards
  custom_wards: false

split:
  test_size: 0.2
  val_size: 0.2
  folds: 5
  group_by_ward: true

train:
  # One of services, socioeconomic_status, government_satisfaction,
  # life_satisfaction, health, safety, participation, qol_index
  label: qol_index
  # Augment training data?
  augment_training_data: 1
  # Loss to use for training
  loss: mean_squared_error
  # Learning rate to use for training
  learning_rate: 0.01
  # Whether to implement k-fold cross validation
  cross_val: false
  # Number epochs
  epochs: 1
  # Model name. One of: resnet50v2, vgg16
  model_name: resnet50v2

model:
  resnet50v2:
    train_base: false
  vgg16:
    fc_units: 256
    dropout_rate: 0.2
