[tool.poetry]
name = "measuring-quality-of-life"
version = "0.1.0"
description = ""
authors = ["Emily <emilyrosesteyn@gmail.com>"]
license = "GNU General Public License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyter = "^1.0.0"
matplotlib = "^3.7.0"
pandas = "^1.5.3"
rasterio = "^1.3.6"
geopandas = "^0.12.2"
rioxarray = "^0.14.1"
earthpy = "^0.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
